workflows:
  android-workflow:
    name: Android build workflow
    scripts:
      - ./gradlew clean
      - ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
